config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'

  root 'pages#index'
  get 'pages/help'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#delete'

  get 'comments/index'
  get '/comments', to:'comments#new'
  post '/comments', to:'comments#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get "/users/search" => "users#search" ,as: "search"
  resources :users do
    resources :user_comments
  end

  resources :topics
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
 validates :user_id, presence: true
 validates :description, presence: true
 validates :image, presence: true
 belongs_to :user

 mount_uploader :image, ImageUploader

 #def user
 has_many :favorites
 has_many :favorite_users, through: :favorites, source: 'user'
 #end
 has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  VALID_PASSWORD_REGEX=/\A(?=.*?[a-z])(?=.*?\d)(?=.*?[!-\/:-@\[-`{-~])[!-~]{8,32}+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX }

  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}

  validates :name, presence: true, length: { maximum: 30 }

  has_secure_password
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites,source: "topic"
  has_many :comments
  has_many :comment_topics, through: :comments, source: 'topic'

  has_many :sender_comments,class_name: "UserComment",foreign_key: "sender_id",dependent: :destroy
  has_many :senders,through: :sender_comments,source: :sender
  has_many :receiver_comments,class_name: "UserComment",foreign_key: "receiver_id",dependent: :destroy
  has_many :senders,through: :receiver_comments,source: :receiver

  def self.search(search)
    if search
      User.where(['name LIKE ? OR email LIKE ? ', "%#{search}%","%#{search}%"])
    else
      Post.all
    end
  end

end

app/models/user_comment.rb
class UserComment < ApplicationRecord
  belongs_to :sender,class_name: "User"
  belongs_to :receiver,class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
  helper_method :current_user,:logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comment_topics = current_user.comment_topics
  end

  def new
    @comment = Comment.new
    @topic_id = params[:topic_id]
  end

  def create
    #binding.pry
    comment = Comment.new
    comment.user_id = current_user.id
    comment.topic_id = params[:topic_id]
    comment.comment = params[:comment][:comment]
    if comment.save
      redirect_to topics_path, success: 'コメントに成功しました'
    else
      redirect_to topics_path, danger: 'コメントに失敗しました'
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end

  def delete
    favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    if favorite.destroy
      redirect_to topics_path, success: 'お気に入りを削除しました'
    else
      redirect_to topics_path, danger: 'お気に入りの削除に失敗しました'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
     log_in user
     redirect_to root_path, success: 'ログインに成功しました'
    else
     flash.now[:danger] = 'ログインに失敗しました'
     render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  private
  def log_in(user)
   session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
      @topics = Topic.all.includes(:favorite_users)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
  def new
    @user = User.find_by(id: params[:user_id])
    @user_comment=UserComment.new
  end
  def create
    if @user = User.find_by(id: params[:user_id])
      if UserComment.create(sender_id: current_user.id,receiver_id: @user.id,body: params[:user_comment][:body])
        redirect_to users_path,success: "ユーザーにコメントしました"
      else
        redirect_to users_path,danger: "コメントに失敗しました。"
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
       redirect_to root_path, success: '登録が完了しました'
      else
       flash.now[:danger] = "登録に失敗しました"
       render :new
      end
  end
  def show
    @user=User.find_by(id: params[:id])
  end

  def edit
    @user=User.find_by(id: params[:id])
  end
  def update
    if current_user && current_user.authenticate(user_params[:password])
      current_user.update_attributes(user_params)
      redirect_to user_path(current_user)
    else
      @user = current_user
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if current_user == @user
      current_user.delete
      redirect_to root_path,success: "退会しました"
    else
      redirect_to user_path(current_user),danger: "退会に失敗しました"
    end
  end
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @users = User.search(params[:search])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #def current_user
    #@current_user ||= User.find_by(id: session[:user_id])
  #end

  #def logged_in?
    #!current_user.nil?
  #end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @comment_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
            <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
            <%= topic.description %>
            </p>
　　　　　　　<% topic.comments.each do |comment| %>
            　<%= comment.comment %><br/>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Comment</h1>
        <%= form_for @comment do |f| %>

          <div class="form-group">
            <%= f.label :comment %>
            <%= f.text_area :comment, class: 'form-control' %>
          </div>
          <input type="hidden" name="topic_id" id="topic_id" value="<%= @topic_id.to_s.html_safe =%>" />
          <% if logged_in?  %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <%= image_tag 'icons/heart-pink.png', class: 'topic-index-icon' %>
              <% end %>
            <% end %>
            <%= topic.favorites.count %>

            <%= link_to comments_path(topic_id: topic.id), method: :get do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
            <% topic.comments.each do |comment| %>
            　<%= comment.comment %><br/>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <% if logged_in?  %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_comments/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white"><%= @user.name %>にコメントする</h1>
          <%= form_for @user_comment,url: user_user_comments_path(@user) do |f| %>
          <div class="form-group">
            <%= f.label "コメント", class: 'text-white' %>
            <%= f.text_field :body, class: 'form-control' %>
          </div>

        <%= f.submit "コメントを投稿する", class: 'btn-block btn-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">プロフィールの更新</h1>
          <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

        <%= f.submit "更新", class: 'btn-block btn-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="topic-index-wrapper">
  <h2 style="text-align:center;">ユーザーの一覧</h2>
  <div class="col-md-6 col-md-offset-3">
    <p>検索</p>
    <%= form_tag(search_path,:method => 'get') do %>
      <%= text_field_tag :search,"",class:"form-control" %>
      <%= submit_tag 'ユーザーを検索', :name => nil,class:"btn btn-info" %>
    <% end %>
  </div>
  <% @users.each do |user| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="topic-index-single">
          <h2 class="topic-author">
            <%= user.name %>
          </h2>
          <p><%= user.email %></p>
          <hr>
          <h3>コメント</h3>
          <% user.receiver_comments.each do |comment| %>
            <p>名前：<%= comment.sender.name %></p>
            <p><%= comment.body %></p>
          <% end %>
          <%= link_to "コメントする",new_user_user_comment_path(user.id),class: "btn btn-success" unless user == current_user%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
          <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

        <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class="topic-index-wrapper">
  <h2 style="text-align:center;">ユーザーの一覧</h2>
  <div class="col-md-6 col-md-offset-3">
    <p>検索</p>
    <%= form_tag(search_path,:method => 'get') do %>
      <%= text_field_tag :search,"",class:"form-control" %>
      <%= submit_tag 'ユーザーを検索', :name => nil,class:"btn btn-info" %>
    <% end %>
  </div>
  <% @users.each do |user| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="topic-index-single">
          <h2 class="topic-author">
            <%= user.name %>
          </h2>
          <p><%= user.email %></p>
          <hr>
          <h3>コメント</h3>
          <% user.receiver_comments.each do |comment| %>
            <p>名前：<%= comment.sender.name %></p>
            <p><%= comment.body %></p>
          <% end %>
          <%= link_to "コメントする",new_user_user_comment_path(user.id),class: "btn btn-success" unless user == current_user%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="" style="margin-top:100px;">

  <div class="panel col-md-offset-3 col-md-6" style="text-align:center;">
    <h3><%= @user.name %></h3>
    <p><%= @user.email %></p>
    <%= link_to "プロフィールの編集",edit_user_path(@user),class:"btn btn-info" %>
    <br>
    <br>
    <%= link_to "退会する",user_path(@user),method: :delete,class:"btn btn-danger" %>
  </div>
</div>